# Generated by Django 6.0.4 on 2026-04-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
